apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4Gi
            cpu: 1000m
          requests:
            memory: 2Gi
            cpu: 100m
        env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver
                key: SA_PASSWORD
        ports:
          - containerPort: 1433
            protocol: TCP
          - containerPort: 5433
            protocol: TCP
        volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: sqlserverdb-data
          - mountPath: /var/opt/mssql/log
            name: sqlserverdb-log
          - mountPath: /var/opt/mssql/secrets
            name: sqlserver-secrets
          - mountPath: /etc/krb5.conf
            name: sql-cm-krb5
      volumes:
      - name: sqlserverdb-data
        persistentVolumeClaim:
          claimName: sqlserverdb-data
      - name: sqlserverdb-log
        persistentVolumeClaim:
          claimName: sqlserverdb-log
      - name: sqlserver-secrets
        configMap:
          name: sql-cm-keytab
          key: mssql.keytab
      - name: sqlserver-krb5
        configMap:
          name: sql-cm-krb5
          key: krb5.conf
