kind: Kustomization
resources:
- database
secretGenerator:
- name: sqlserver
  literals:
    - SA_PASSWORD=Password123!!
configMapGenerator:
- name: sql-cm-keytab
  files:
  - mssql.keytab
- name: sql-cm-krb5
  files:
  - krb5.conf
